export const videos = [
  {
    id: 1,
    title: "React Tutorial for Beginners",
    description: "Learn React from scratch in this comprehensive tutorial. We'll cover components, hooks, state management, and more.",
    thumbnail: "https://picsum.photos/seed/react/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder1",
    channel: "Code Master",
    channelId: "channel1",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=CodeMaster",
    views: "100K",
    likes: 1500,
    dislikes: 50,
    timestamp: "2 days ago",
    category: "Programming",
    comments: [
      {
        id: "comment1",
        userId: "user1",
        username: "WebDev123",
        userAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=WebDev123",
        content: "Great tutorial! Really helped me understand React better.",
        timestamp: "1 day ago",
        likes: 25
      }
    ]
  },
  {
    id: 2,
    title: "Latest Pop Hits 2025 Mix",
    description: "The hottest pop hits of 2025 all in one mix. Perfect for parties and workouts!",
    thumbnail: "https://picsum.photos/seed/music/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder2",
    channel: "Music Now",
    channelId: "channel2",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=MusicNow",
    views: "250K",
    likes: 3000,
    dislikes: 100,
    timestamp: "1 week ago",
    category: "Music",
    comments: []
  },
  {
    id: 3,
    title: "Pro Gaming Tips & Tricks",
    description: "Master your favorite games with these pro tips and tricks. From strategy to execution, we've got you covered.",
    thumbnail: "https://picsum.photos/seed/gaming/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder3",
    channel: "Gaming Pro",
    channelId: "channel3",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=GamingPro",
    views: "75K",
    likes: 1200,
    dislikes: 30,
    timestamp: "3 days ago",
    category: "Gaming",
    comments: []
  },
  {
    id: 4,
    title: "Easy Cooking Recipes",
    description: "Delicious and easy-to-follow recipes for every meal. Perfect for beginners and experienced cooks alike.",
    thumbnail: "https://picsum.photos/seed/cooking/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder4",
    channel: "Cooking with Joy",
    channelId: "channel4",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=CookingWithJoy",
    views: "120K",
    likes: 2000,
    dislikes: 75,
    timestamp: "5 days ago",
    category: "Cooking",
    comments: []
  },
  {
    id: 5,
    title: "Advanced JavaScript Concepts",
    description: "Dive deep into advanced JavaScript concepts and techniques. Perfect for developers looking to level up their skills.",
    thumbnail: "https://picsum.photos/seed/javascript/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder5",
    channel: "JS Mastery",
    channelId: "channel5",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=JSMastery",
    views: "80K",
    likes: 1700,
    dislikes: 60,
    timestamp: "1 day ago",
    category: "Programming",
    comments: []
  },
  {
    id: 6,
    title: "Travel Vlog: Paris 2025",
    description: "Join us on an adventure through Paris in 2025. Discover the best spots, food, and experiences the city has to offer.",
    thumbnail: "https://picsum.photos/seed/travel/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder6",
    channel: "Travel With Me",
    channelId: "channel6",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=TravelWithMe",
    views: "300K",
    likes: 5000,
    dislikes: 200,
    timestamp: "4 days ago",
    category: "Travel",
    comments: []
  },
  {
    id: 7,
    title: "Top 10 Sports Moments 2025",
    description: "Relive the top 10 sports moments of 2025. From incredible plays to unforgettable victories, it's all here.",
    thumbnail: "https://picsum.photos/seed/sports/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder7",
    channel: "Sports Central",
    channelId: "channel7",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=SportsCentral",
    views: "500K",
    likes: 8000,
    dislikes: 300,
    timestamp: "2 weeks ago",
    category: "Sports",
    comments: []
  },
  {
    id: 8,
    title: "Machine Learning Basics",
    description: "An introduction to machine learning concepts and techniques. Perfect for beginners looking to get started in the field.",
    thumbnail: "https://picsum.photos/seed/ml/320/180",
    videoUrl: "https://www.youtube.com/watch?v=placeholder8",
    channel: "Tech Education",
    channelId: "channel8",
    channelAvatar: "https://api.dicebear.com/7.x/avatars/svg?seed=TechEducation",
    views: "90K",
    likes: 1300,
    dislikes: 40,
    timestamp: "6 days ago",
    category: "Education",
    comments: []
  }
];